version: '2'

services:

  awsenv:
    build: ./
    image: base2/awsenv
    environment:
      LOG_LEVEL: debug
      SSM_PATH: /my-app/production/prod1
      OUTPUT: shell
      AWS_REGION: ap-southeast-2

  test:
    image: debian:jessie
    tty: true
    volumes_from:
      - awsenv
    command: bash -c "eval $$(cat /ssm/.env) && printenv"
